### ISSUE TITLE
Powershell : Cursor shape does not recover after exiting vim

### ISSUE THREAD

**Issue by PrashanthaTP** [PrashanthaTP/dotfiles#5]
# Issue Description
After exiting vim cursor is in block state itself

![image](https://user-images.githubusercontent.com/52926365/130332269-7e16ab0f-2bba-48c6-973c-f4ba60b401a6.png)

# Expected
![image](https://user-images.githubusercontent.com/52926365/130332295-f3205c4b-ae08-4eee-8b69-e38490574c67.png)

# More Info
+ https://github.com/microsoft/terminal/issues/4335

**Comment by younger-1** [comment]
In powershell, `autocmd VimLeave * set guicursor=a:ver25` works only for neovim but not vim. Is there a way to restore the cursor to default in vim?

**Comment by PrashanthaTP** [comment]
Hmmm, 
did you try one of these autocommands

```vim
" https//vim.fandom.com/wiki/Configuring_the_cursor 
" 1 or 0 -> blinking block
 " 2 solid block
 " 3 -> blinking underscore 
" 4 solid underscore " Recent versions of xterm (282 or above) also support 
" 5 -> blinking vertical bar 
" 6 -> solid vertical bar 

autocmd VimLeave * silent !echo -ne "\e[6 q" autocmd VimLeave * silent !printf "\e[6 q"

```

**Comment by younger-1** [comment]
🥲 these autocmds only works in WSL(ubuntu/arch..), not in powershell

**Comment by Xiaorui-Huang** [comment]
@younger-1 
Since I wanted to use the default vintage cursor ( ▃ ), requiring "\e[0 q", so none of the above worked for me, but I have found a workaround by resetting the cursor whenever the prompt is rendered

if you use the default prompt, put this in your powershell profile

    function prompt{
        ...
        Write-Host -NoNewLine "`e[0 q"
    }


If you use oh-my-posh

    function Set-PromptContext{
       ...
       Write-Host -NoNewLine "`e[0 q"
    }
    New-Alias -Name 'Set-PoshContext' -Value 'Set-PromptContext' -Scope Global -Force
